# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage precision and rounding
coverage:
  precision: 2
  round: down
  range: "60...90"

  # Status checks for PR and commits
  status:
    # Project coverage (overall codebase)
    project:
      default:
        target: auto           # Maintain current coverage
        threshold: 1%          # Allow 1% decrease
        base: auto             # Compare against base branch
        if_ci_failed: error    # Require CI to pass

    # Patch coverage (new changes only)
    patch:
      default:
        target: 70%            # New code should have 70%+ coverage
        threshold: 5%          # Allow some flexibility
        base: auto
        if_ci_failed: error

# Ignore patterns - exclude test files and test-only packages
ignore:
  - "**/*_test.go"              # All test files
  - "**/testutil/**"            # Test utility package
  - "**/integration/**"         # Integration test package
  - "**/*.pb.go"                # Generated protobuf files (if any)
  - "**/vendor/**"              # Vendor directory (if any)
  - "**/mocks/**"               # Mock files (if any)

# Pull request comment configuration
comment:
  layout: "header,diff,changes,tree"
  behavior: default             # Comment on all PRs
  require_changes: false        # Comment even if no coverage change
  require_base: false           # Comment even without base coverage
  require_head: true            # Require head coverage to exist

# GitHub integration
github_checks:
  annotations: true             # Show annotations on PR files

# Codecov flags (for future use with parallel test runs)
flags:
  unit:
    paths:
      - "*.go"
      - "internal/**/*.go"
    carryforward: true
  integration:
    paths:
      - "integration/**/*.go"
    carryforward: true

# Parsing configuration
parsers:
  go:
    partials_as_hits: true      # Count partial coverage as hits

# Codecov behavior
codecov:
  require_ci_to_pass: true      # Require CI before processing
  notify:
    wait_for_ci: true           # Wait for CI to complete
