version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - unused
  disable:
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - govet
