version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - unused
  disable:
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - govet
      - path: integration/aws_test.go
        # Ignore AWS SDK v2 deprecation warnings (SA1019) in integration tests
        # These will be fixed when we rewrite to service-specific endpoints  
        text: "SA1019"
        linters:
          - staticcheck  
